Chuan/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls', namespace='index')),
    path('users/', include('users.urls', namespace='users')),
    path('merchant/', include('merchant.urls', namespace='merchant')),
    path('orders/', include('orders.urls', namespace='orders'))
]

apps/merchant/urls.py
from django.urls import path

from merchant import views

app_name = 'merchant'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('register/', views.register, name='register'),
    path('checkname/', views.check_merchant_name, name='check_merchant_name'),
    path('checkidCard/', views.check_id_card, name='check_id_card'),
    path('checkphone/', views.check_phone, name='check_phone'),
    path('checkemail/', views.check_email, name='check_email'),
    path('login/', views.login, name='login'),
    path('mine/', views.mine, name='mine'),
    path('logout/', views.logout, name='logout'),
    path('publish/', views.publish, name='publish'),
    path('mineorder/', views.mine_order, name='mine_order'),
]

apps/merchant/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models


class Merchant(models.Model):
    m_merchantName = models.CharField(max_length=32, unique=True, verbose_name='商家名')
    m_password = models.CharField(max_length=256, verbose_name='商家密码')
    m_phone = models.CharField(max_length=13, unique=True, verbose_name='商家手机号')
    m_email = models.CharField(max_length=64, unique=True, verbose_name='商家邮箱号')
    m_icon = models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='商家头像')
    m_idCard = models.CharField(max_length=18, unique=True, verbose_name='商家身份证')
    m_idCard_front = models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='商家身份证正面照')
    m_idCard_back = models.ImageField(upload_to='photo/%Y/%m/%d', verbose_name='商家身份证背面照')
    is_active = models.BooleanField(default=False, verbose_name='商家激活状态')
    is_delete = models.BooleanField(default=False, verbose_name='商家是否删除')

    class Meta:
        db_table = 'chuan_merchant'


class Project(models.Model):
    p_title = models.CharField(max_length=32, verbose_name='项目名称')
    p_introText = models.TextField(verbose_name='项目简介')
    p_classify = models.CharField(max_length=16, verbose_name='项目分类')
    p_introImg = models.ImageField(upload_to='project/%Y/%m/%d', verbose_name='简介图片')
    p_days = models.IntegerField(default=30, verbose_name='众筹期限')
    p_follow = models.IntegerField(default=0, verbose_name='关注数')
    p_target = models.IntegerField(verbose_name='目标金额')
    p_already = models.IntegerField(default=0, verbose_name='已筹金额')
    p_status = models.CharField(default='审核中', max_length=20, verbose_name='项目状态')
    p_merchant = models.ForeignKey(Merchant, on_delete=models.CASCADE, verbose_name='商家ID')
    p_time = models.DateTimeField(auto_now_add=True, verbose_name='申请时间')

    class Meta:
        db_table = 'chuan_project'


class ProjectDetail(models.Model):
    p_project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='项目ID')
    p_detail = models.ImageField(upload_to='project/%Y/%m/%d', verbose_name='详细图片')

    class Meta:
        db_table = 'chuan_projectDetail'


class Goods(models.Model):
    g_title = models.CharField(max_length=32, verbose_name='商品名称')
    g_img = models.ImageField(upload_to='project/%Y/%m/%d', verbose_name='商品图片')
    g_detail = models.TextField(verbose_name='商品详细')
    g_price = models.IntegerField(verbose_name='商品价格')
    g_sold = models.IntegerField(default=0, verbose_name='商品已定数量')
    g_stock = models.IntegerField(default=99999999, verbose_name='商品库存')
    g_postage = models.IntegerField(default=0, verbose_name='配送费')
    g_project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name='商品项目')

    class Meta:
        db_table = 'chuan_goods'

apps/orders/models.py
from django.db import models

from merchant.models import Goods, Project, Merchant
from orders.views_constant import ORDER_STATUS_NOT_PAY
from users.models import Users


class Cart(models.Model):
    c_user = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name='用户ID')
    c_goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='商品ID')

    c_goods_num = models.IntegerField(default=1, verbose_name='商品总数')
    c_is_select = models.BooleanField(default=True, verbose_name='商品是否选中')

    class Meta:
        db_table = 'chuan_cart'


class Order(models.Model):
    o_user = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name='用户ID')
    o_merchant = models.ForeignKey(Merchant, on_delete=models.CASCADE, verbose_name='商家ID')
    o_price = models.FloatField(default=0, verbose_name='订单价格')
    o_time = models.DateTimeField(auto_now_add=True, verbose_name='下单时间')
    o_status = models.IntegerField(default=ORDER_STATUS_NOT_PAY, verbose_name='订单状态')

    class Meta:
        db_table = 'chuan_order'


class OrderGoods(models.Model):
    o_order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='订单ID')
    o_goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='订单商品')
    o_goods_num = models.IntegerField(default=1, verbose_name='商品数量')

    class Meta:
        db_table = 'chuan_orderGoods'

apps/users/models.py
from django.db import models


class Users(models.Model):
    u_username = models.CharField(max_length=32, unique=True, verbose_name='用户名')
    u_password = models.CharField(max_length=256, verbose_name='用户密码')
    u_email = models.CharField(max_length=64, unique=True, verbose_name='用户邮箱')
    u_icon = models.ImageField(upload_to='icons/%Y/%m/%d', verbose_name='用户头像')
    is_active = models.BooleanField(default=False, verbose_name='用户激活状态')
    is_delete = models.BooleanField(default=False, verbose_name='用户是否删除')

    class Meta:
        db_table = 'chuan_user'


class Address(models.Model):
    a_name = models.CharField(max_length=16, verbose_name='收货姓名')
    a_phone = models.CharField(max_length=11, verbose_name='收货手机号码')
    a_address = models.CharField(max_length=256, verbose_name='收货地址')
    a_code = models.CharField(max_length=6, verbose_name='邮政编码')
    a_is_default = models.BooleanField(default=True, verbose_name='默认地址')
    a_user = models.ForeignKey(Users, verbose_name='用户ID', on_delete=models.CASCADE)

    class Meta:
        db_table = 'chuan_address'


class AddressCopy(models.Model):
    a_name = models.CharField(max_length=16, verbose_name='收货姓名')
    a_phone = models.CharField(max_length=11, verbose_name='收货手机号码')
    a_address = models.CharField(max_length=256, verbose_name='收货地址')
    a_code = models.CharField(max_length=6, null=True, verbose_name='邮政编码')
    a_order = models.ForeignKey('orders.Order', verbose_name='订单ID', on_delete=models.CASCADE)

    class Meta:
        db_table = 'chuan_addressCopy'

apps/merchant/views.py
from django.contrib.auth.hashers import check_password, make_password
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse

from Chuan.settings import MEDIA_KEY_PREFIX, MEDIA_ROOT
from merchant.models import Merchant, Project, Goods, ProjectDetail
from merchant.views_contant import HTTP_ID_CART_EXIST, HTTP_MERCHANT_EXIST, HTTP_PHONE_EXIST, HTTP_EMAIL_EXIST
from merchant.views_helper import get_merchant_login_status, get_merchant_order_status
from orders.models import Order
from orders.views_helper import get_order_status


def hello(request):
    return HttpResponse("hello")


def register(request):
    if request.method == "GET":
        data = {
            'title': '商家注册'
        }
        return render(request, 'merchant/register.html', context=data)
    elif request.method == "POST":
        merchantName = request.POST.get('merchantName')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        password = request.POST.get('password')
        idCard = request.POST.get('idCard')
        idCard_front = request.FILES.get('idCard_front')
        idCard_back = request.FILES.get('idCard_back')
        icon = request.FILES.get('icon')

        password = make_password(password)

        merchant = Merchant()
        merchant.m_merchantName = merchantName
        merchant.m_phone = phone
        merchant.m_email = email
        merchant.m_password = password
        merchant.m_idCard = idCard
        merchant.m_idCard_front = idCard_front
        merchant.m_idCard_back = idCard_back
        merchant.m_icon = icon
        merchant.save()
        return render(request, 'merchant/login.html')


def check_merchant_name(request):
    name = request.GET.get('merchantName')
    merchant = Merchant.objects.filter(m_merchantName=name)
    data = {
        'status': 200,
        'msg': '商家名可用'
    }
    if merchant.exists():
        data['status'] = HTTP_MERCHANT_EXIST
        data['msg'] = '商家名已存在'
    return JsonResponse(data=data)


def check_id_card(request):
    idCart = request.GET.get('idCard')
    print(idCart)
    merchant = Merchant.objects.filter(m_idCard=idCart)
    data = {
        'status': 200,
        'msg': '身份证可用'
    }
    if merchant.exists():
        print('ccc')
        data['status'] = HTTP_ID_CART_EXIST
        data['msg'] = '身份证已存在'
    return JsonResponse(data=data)


def check_phone(request):
    phone = request.GET.get('phone')
    merchant = Merchant.objects.filter(m_phone=phone)
    data = {
        'status': 200,
        'msg': '手机号可用'
    }
    if merchant.exists():
        data['status'] = HTTP_PHONE_EXIST
        data['msg'] = '手机号已存在'
    return JsonResponse(data=data)


def check_email(request):
    email = request.GET.get('email')
    merchant = Merchant.objects.filter(m_email=email)
    data = {
        'status': 200,
        'msg': '邮箱号可用'
    }
    if merchant.exists():
        data['status'] = HTTP_EMAIL_EXIST
        data['msg'] = '邮箱号已存在'
    return JsonResponse(data=data)


def login(request):
    if request.method == "GET":
        error_message = request.session.get('error_message')
        data = {
            'title': '商家登录'
        }
        if error_message:
            del request.session['error_message']
            data['error_message'] = error_message
        return render(request, 'merchant/login.html', context=data)
    elif request.method == "POST":
        merchantName = request.POST.get('merchantName')
        password = request.POST.get('password')
        merchants = Merchant.objects.filter(
            Q(m_phone=merchantName) | Q(m_email=merchantName) | Q(m_merchantName=merchantName))
        if merchants.exists():
            merchant = merchants.first()
            if check_password(password, merchant.m_password):
                if merchant.is_active:
                    request.session['merchant_id'] = merchant.id
                    return redirect(reverse('merchant:mine'))
                else:
                    request.session['error_message'] = '用户未激活'
                    return redirect(reverse('merchant:login'))
            else:
                request.session['error_message'] = '密码错误'
                return redirect(reverse('merchant:login'))
        else:
            request.session['error_message'] = '用户不存在'
            return redirect(reverse('merchant:login'))


def mine(request):
    merchant_id = request.merchant.id
    data = {
        'title': '我的中心',
        'is_login': True,
        'MEDIA_KEY_PREFIX': MEDIA_KEY_PREFIX,
    }
    merchant = Merchant.objects.get(pk=merchant_id)
    data['merchantName'] = merchant.m_merchantName
    data['m_Icon'] = merchant.m_icon

    return render(request, 'merchant/mine.html', context=data)


def logout(request):
    request.session.flush()
    return redirect(reverse('merchant:mine'))


def publish(request):
    if request.method == "GET":
        data = {
            'title': '发起众筹',
            'is_login': True
        }
        merchant_id = request.merchant.id
        merchant = Merchant.objects.get(pk=merchant_id)
        data['merchantName'] = merchant.m_merchantName
        return render(request, 'merchant/publish.html', context=data)
    elif request.method == "POST":
        p_title = request.POST.get('p_title')
        p_introText = request.POST.get('p_introText')
        p_classify = request.POST.get('p_classify')
        p_introImg = request.FILES.get('p_introImg')
        p_detail = request.FILES.getlist('p_detail')
        p_days = request.POST.get('p_days')
        p_target = request.POST.get('p_target')
        g_title = request.POST.getlist('g_title')
        g_detail = request.POST.getlist('g_detail')
        g_price = request.POST.getlist('g_price')
        g_stock = request.POST.getlist('g_stock')
        g_img = request.FILES.getlist('g_img')

        project = Project()
        project.p_title = p_title
        project.p_introText = p_introText
        project.p_classify = p_classify
        project.p_days = p_days
        project.p_target = p_target
        project.p_merchant = request.merchant
        project.p_introImg = p_introImg
        project.save()
        # project.p_detail = p_detail
        for detailt in p_detail:
            detailtImg = ProjectDetail()
            detailtImg.p_project = project
            detailtImg.p_detail = detailt
            detailtImg.save()


        for i in range(len(g_title)):
            goods = Goods()
            goods.g_project_id = project.id
            goods.g_title = g_title[i]
            goods.g_detail = g_detail[i]
            goods.g_price = g_price[i]
            goods.g_stock = g_stock[i]
            goods.g_img = g_img[i]
            goods.save()

        return redirect(reverse('merchant:mine'))


def mine_order(request):
    merchant_id = request.merchant
    print(merchant_id)
    orders = Order.objects.filter(o_merchant_id=merchant_id).exclude(o_status=1).order_by('-id')
    for order in orders:
        order.o_status = get_merchant_order_status(order.o_status)

    data = {
        'title': '我的订单',
        'is_login': True,
        'orders': orders,
        'MEDIA_KEY_PREFIX': MEDIA_KEY_PREFIX,
    }
    # 获取登录信息
    merchant = Merchant.objects.get(pk=merchant_id.id)
    data['merchantName'] = merchant.m_merchantName
    return render(request, 'merchant/mine_order.html', context=data)

templates/merchant/login.html
{% extends 'base_merchant.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'chuan/merchant/css/login.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'chuan/merchant/js/login.js' %}"></script>
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="text-right merchant">
            <a href="{% url 'users:login' %}">
                <button class="btn btn-info">去用户版</button>
            </a>
        </div>

        <div class="all-center">
            <div class="login-logo">
                <img class="center-block logo-img" src="/static/img/icon/header.png" alt="">
            </div>
            <form method="post" action="{% url 'merchant:login' %}" onsubmit="return parse_data()">

                {% csrf_token %}

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2 col-md-push-3 text-tip">
                            <label for="merchantName_input">商家名</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="merchantName" type="text" class="form-control" id="merchantName_input"
                                   placeholder="商家名/手机号/邮箱">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="username_info" class="text-tip error_message">
                                {% if error_message == '用户不存在' or error_message == '用户未激活' %}
                                    {{ error_message }}
                                {% endif %}
                            </span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-3 text-tip">
                            <label for="password_input">密码</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="password" type="password" class="form-control" id="password_input"
                                   placeholder="请输入密码">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="password_info" class="text-tip error_message">
                                {% if error_message == '密码错误' %}
                                    {{ error_message }}
                                {% endif %}
                            </span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-7 col-md-push-3 loginbtn">
                            <button type="submit" class="btn btn-success btn-lg btn-block">登录</button>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-7 col-md-push-4 registerbtn">
                            <h2>未拥有账号><a href="{% url 'merchant:register' %}">去注册</a></h2>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/merchant/mine.html
{% extends 'base_merchant.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static '/chuan/merchant/css/mine.css' %}">
{% endblock %}

{% block main %}
    {{ block.super }}
    <div class="userIcon">
        <a href="">
            <img src="{{ MEDIA_KEY_PREFIX }}{{ m_Icon }}" alt="">
        </a>
    </div>
{% endblock %}


{#{% block content %}#}
{#    {% if is_login %}#}
{#        <p>{{ merchantName }}</p>#}
{#        <p><a href="{% url 'merchant:publish' %}">发起众筹</a></p>#}
{#        <p><a href="{% url 'merchant:logout' %}">退出</a></p>#}
{#    {% endif %}#}
{#{% endblock %}#}

templates/merchant/mine_order.html
{% extends 'merchant/mine.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static '/chuan/merchant/css/mine_order.css' %}">
{% endblock %}

{% block main %}
    <div class="mainTip">
        <div>我的订单</div>
    </div>

    <div class="myOrder">
        <div class="mt">
            <ul>
                <li><a href="#" class="selected">全部订单</a></li>
                <li><a href="#" class="notSelect">待发款</a></li>
                <li><a href="#" class="notSelect">已完成</a></li>
                <li><a href="#" class="notSelect">已评价</a></li>
            </ul>
        </div>


        <div class="mc">

            <table>
                <thead>
                <tr>
                    <th>订单详细</th>
                    <th>收货人</th>
                    <th>金额</th>
                    <th>订单状态</th>
                    <th>操作</th>
                </tr>
                </thead>

                {% for order in orders %}
                    <tbody>
                    <tr class="sep-row">
                        <td colspan="5"></td>
                    </tr>
                    <tr class="tr-th">
                        <td colspan="5"><p>{{ order.o_time }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;订单号:{{ order.id }}</p></td>
                    </tr>


                    {% for goods in order.ordergoods_set.all %}
                        <tr class="tr-bd">
                            <td class="goods-detail">
                                <div class="goods-item">
                                    <div class="g-img"><img src="{{ MEDIA_KEY_PREFIX }}{{ goods.o_goods.g_img }}" alt=""
                                                            class="goods-img"></div>
                                    <div class="p-msg"><a href="">
                                        {{ goods.o_goods.g_project.p_merchant.m_merchantName }}&nbsp;&nbsp;{{ goods.o_goods.g_title }}</a>
                                    </div>
                                    <div class="goods-number">x{{ goods.o_goods_num }}</div>

                                </div>
                            </td>

                            {% if forloop.counter == 1 %}
                                <td rowspan="{{ order.ordergoods_set.all.count }}">{{ order.addresscopy_set.first.a_name }}</td>
                                <td rowspan="{{ order.ordergoods_set.all.count }}">总额 ¥{{ order.o_price }} <br> <br>
                                    在线支付
                                </td>
                                <td rowspan="{{ order.ordergoods_set.all.count }}">{{ order.o_status|first }} <br> <br> <a href="#">{{ order.o_status|last }}</a></td>
                                <td rowspan="{{ order.ordergoods_set.all.count }}">查看发票</td>
                            {% endif %}

                        </tr>
                    {% endfor %}

                    </tbody>
                {% endfor %}


            </table>
        </div>

    </div>

{% endblock %}

templates/merchant/register.html
{% extends 'base_merchant.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'chuan/merchant/css/reg.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'chuan/merchant/js/reg.js' %}"></script>
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="text-right merchant">
            <a href="{% url 'users:register' %}">
                <button class="btn btn-info">去用户版</button>
            </a>
        </div>

        <div class="all-center">
            <div class="reg-logo">
                <img class="center-block logo-img" src="/static/img/icon/header.png" alt="">
            </div>
            <form method="post" action="{% url 'merchant:register' %}" onsubmit="return check()"
                  enctype="multipart/form-data">

                {% csrf_token %}

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2 col-md-push-2 text-tip">
                            <label for="merchantName_input">商家名</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="merchantName" type="text" class="form-control" id="merchantName_input"
                                   placeholder="请输入商家名">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="merchantName_info" class="text-tip"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-2 text-tip">
                            <label for="phone_input">手机号码</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="phone" type="text" class="form-control" id="phone_input" placeholder="请输入手机号码">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="phone_info" class="text-tip"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-2 text-tip">
                            <label for="email_input">邮箱</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="email" type="text" class="form-control" id="email_input" placeholder="请输入邮箱">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="email_info" class="text-tip"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-2 text-tip">
                            <label for="password_input">密码</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="password" type="password" class="form-control" id="password_input"
                                   placeholder="请输入密码">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="password_info" class="text-tip"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-2 text-tip">
                            <label for="password_confirm_input">确认密码</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="password_confirm" type="password" class="form-control"
                                   id="password_confirm_input"
                                   placeholder="请再次输入密码">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="password_confirm_info" class="text-tip"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-2 text-tip">
                            <label for="idCard">身份证号码</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="idCard" type="text" class="form-control" id="idCard_input"
                                   placeholder="请输入身份证">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="idCard_info" class="text-tip"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-2 text-tip id-text">
                            <label for="idCard_front">身份证正面照</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="idCard_front" type="file" id="idCard_front_input">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="idCard_front_info"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-2 text-tip id-text">
                            <label for="idCard_back">身份证背面照</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="idCard_back" type="file" id="idCard_back_input">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="idCard_back_info"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-2 text-tip">
                            <label for="icon">商家头像</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="icon" type="file" id="icon_input">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="icon_info"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-7 col-md-push-3 registerbtn">
                            <button type="submit" class="btn btn-primary btn-lg btn-block" id="button">注册</button>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-7 col-md-push-5 registerbtn">
                            <h2>已有账号><a href="{% url 'merchant:login' %}">去登录</a></h2>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
{% endblock %}