Chuan/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls', namespace='index')),
    path('users/', include('users.urls', namespace='users')),
    path('merchant/', include('merchant.urls', namespace='merchant')),
    path('orders/', include('orders.urls', namespace='orders'))
]

apps/index/urls.py
from django.urls import path

from apps.index import views

app_name = 'index'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('indexs/', views.index, name='indexs'),
    path('search/', views.search, name='search'),
]

apps/merchant/urls.py
from django.urls import path

from merchant import views

app_name = 'merchant'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('register/', views.register, name='register'),
    path('checkname/', views.check_merchant_name, name='check_merchant_name'),
    path('checkidCard/', views.check_id_card, name='check_id_card'),
    path('checkphone/', views.check_phone, name='check_phone'),
    path('checkemail/', views.check_email, name='check_email'),
    path('login/', views.login, name='login'),
    path('mine/', views.mine, name='mine'),
    path('logout/', views.logout, name='logout'),
    path('publish/', views.publish, name='publish'),
    path('mineorder/', views.mine_order, name='mine_order'),
]

apps/orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('project/', views.project, name='project'),
    path('addtocart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('changecartstate/', views.change_cart_state, name='change_cart_state'),
    path('subshopping/', views.sub_subshopping, name='sub_shopping'),
    path('addshopping/', views.add_subshopping, name='add_shopping'),
    path('allselect/', views.all_select, name='all_select'),
    path('ordering/', views.ordering, name='ordering'),
    path('makeorder/', views.make_order, name='make_order'),
    path('orderdetail/', views.order_detail, name='order_detail'),
    path('orderlistnotpay/', views.order_list_not_pay, name='order_list_not_pay'),
    path('payed/', views.payed, name='payed'),
]

apps/users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('checkuser/', views.check_user, name='check_user'),
    path('checkemail/', views.check_email, name='check_email'),
    path('mine/', views.mine, name='mine'),
    path('logout/', views.logout, name='logout'),
    path('activate/', views.activate, name='activate'),
    path('mineorder/', views.mine_order, name='mine_order'),
    path('address/', views.address, name='address'),
    path('deleteaddr/', views.deleteaddr, name='deleteaddr'),
    path('defaultaddr/', views.defaultaddr, name='defaultaddr'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/icon/header.png' %}" type="image/png">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'chuan/main/css/header.css' %}">
    {% block ext_css %}

    {% endblock %}
</head>
<body>

{% block header %}
    <div class="">
        <div class="headerBox">
            <div class="headerTop">
                <div class="headerTopRight">
                    {% if is_login %}
                        <p>您好，<a href="{% url 'users:mine' %}" style="color: #0f0f0f">{{ username }}</a>&nbsp;&nbsp;
                            <a href="{% url 'users:logout' %}" class="textTop">退出登录</a>&nbsp;|&nbsp;
                            <a href="{% url 'users:mine_order' %}" class="textTop">我的订单</a>
                            {% else %}
                        <p>您好，请&nbsp;<a href="{% url 'users:login' %}" class="mine-login">登录</a>&nbsp;&nbsp;
                        <a href="{% url 'users:register' %}" class="textTop">注册</a>&nbsp;|&nbsp;
                        <a href="{% url 'users:login' %}" class="textTop">我的订单</a>
                    {% endif %}
                    <img src="/static/img/icon/horn.png" alt="" id="horn">
                    <a href="#" class="textTop">网站公告</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="logoArea">
            <div class="logo" style="display: block">
                <a href="{% url 'index:indexs' %}"> <img class="logo-img" src="/static/img/icon/indexlogo.jpg"
                                                         alt=""></a>
            </div>
            <div class="logoText">
                <a href="{% url 'users:mine' %}">{{ message }}</a>
            </div>

            <div class="search">
                <div class="searchTab">
                    <input type="text" placeholder="请输入..." name="" id="search-input" value=""/>
                    <button id="search-submit"><i>搜索</i></button>
                </div>
                <div class="cart">
                    <img class="cart-img" src="/static/img/icon/cart.png" alt="">
                    {% if is_login %}
                        <p class="cart-text"><a href="{% url 'orders:cart' %}"
                                                id="cart-aText">购物车(<span>{{ cart_num }}</span>)</a></p>
                    {% else %}
                        <p class="cart-text"><a href="{% url 'orders:cart' %}" id="cart-aText">购物车(<span>0</span>)</a>
                        </p>
                    {% endif %}
                </div>
            </div>

        </div>
        <div class="clearfix"></div>
    </div>
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'chuan/main/js/base.js' %}"></script>
{% block ext_js %}

{% endblock %}
</body>
</html>

templates/base_index.html
{% extends 'base.html' %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

templates/base_main.html
{% extends 'base.html' %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

templates/base_merchant.html
{% extends 'base.html' %}
{% load static %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="">
        <div class="headerBox">
            <div class="headerTop">
                <div class="headerTopRight">
                    {% if is_login %}
                        <p>您好，<a href="{% url 'merchant:mine' %}" style="color: #0f0f0f">{{ merchantName }}</a>&nbsp;&nbsp;
                            <a href="{% url 'merchant:logout' %}" class="textTop">退出登录</a>&nbsp;|&nbsp;
                            <a href="{% url 'users:mine_order' %}" class="textTop">我的订单</a>
                            {% else %}
                        <p>您好，请&nbsp;<a href="{% url 'merchant:login' %}" class="mine-login">登录</a>&nbsp;&nbsp;
                        <a href="{% url 'merchant:register' %}" class="textTop">注册</a>&nbsp;|&nbsp;
                        <a href="{% url 'merchant:login' %}" class="textTop">我的订单</a>
                    {% endif %}
                    <img src="/static/img/icon/horn.png" alt="" id="horn">
                    <a href="#" class="textTop">网站公告</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="logoArea">
            <div class="logo" style="display: block">
                <a href="{% url 'index:indexs' %}"> <img class="logo-img" src="/static/img/icon/indexlogo.jpg"
                                                         alt=""></a>
            </div>
            <div class="logoText">
                <a href="{% url 'users:mine' %}">{{ message }}</a>
            </div>

        </div>
        <div class="clearfix"></div>
    </div>
{% endblock %}

{% block content %}
    <div class="middleBox">
        <div class="middle">
            <div class="menu">

                <dl>
                    <dt>我的众筹</dt>
                    <dd><a href="{% url 'merchant:publish' %}">发起众筹</a></dd>
                    <dd>众筹项目</dd>
                </dl>

                <dl>
                    <dt>订单中心</dt>
                    <dd>
                        <a href="{% url 'merchant:mine_order' %}" id="menuText">我的订单</a>
                    </dd>
                </dl>

                <dl>
                    <dt>设置</dt>
                    <dd>个人信息</dd>
                </dl>
            </div>

            <div class="main">
                {% block main %}

                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base_orders.html
{% extends 'base.html' %}
{% load static %}

{% block ext_js %}
    {{ block.super }}
{% endblock %}

templates/base_project.html
{% extends 'base.html' %}

{% block ext_css %}
    {{ block.super }}
{% endblock %}

templates/base_user.html
{% extends 'base.html' %}
{% load static %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="middleBox">
        <div class="middle">
            <div class="menu">
                <dl>
                    <dt>订单中心</dt>
                    <dd>
                        <a href="{% url 'users:mine_order' %}" id="menuText">我的订单</a>
                    </dd>
                </dl>
                <dl>
                    <dt>我的关注</dt>
                    <dd>关注商品</dd>
                    <dd>关注店铺</dd>
                </dl>
                <dl>
                    <dt>设置</dt>
                    <dd>个人信息</dd>
                    <dd><a href="{% url 'users:address' %}" id="addr-text">收货地址</a></dd>
                </dl>
            </div>

            <div class="main">
                {% block main %}

                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}