Chuan/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls', namespace='index')),
    path('users/', include('users.urls', namespace='users')),
    path('merchant/', include('merchant.urls', namespace='merchant')),
    path('orders/', include('orders.urls', namespace='orders'))
]

apps/index/urls.py
from django.urls import path

from apps.index import views

app_name = 'index'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('indexs/', views.index, name='indexs'),
    path('search/', views.search, name='search'),
]

apps/orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('project/', views.project, name='project'),
    path('addtocart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('changecartstate/', views.change_cart_state, name='change_cart_state'),
    path('subshopping/', views.sub_subshopping, name='sub_shopping'),
    path('addshopping/', views.add_subshopping, name='add_shopping'),
    path('allselect/', views.all_select, name='all_select'),
    path('ordering/', views.ordering, name='ordering'),
    path('makeorder/', views.make_order, name='make_order'),
    path('orderdetail/', views.order_detail, name='order_detail'),
    path('orderlistnotpay/', views.order_list_not_pay, name='order_list_not_pay'),
    path('payed/', views.payed, name='payed'),
]

apps/users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('checkuser/', views.check_user, name='check_user'),
    path('checkemail/', views.check_email, name='check_email'),
    path('mine/', views.mine, name='mine'),
    path('logout/', views.logout, name='logout'),
    path('activate/', views.activate, name='activate'),
    path('mineorder/', views.mine_order, name='mine_order'),
    path('address/', views.address, name='address'),
    path('deleteaddr/', views.deleteaddr, name='deleteaddr'),
    path('defaultaddr/', views.defaultaddr, name='defaultaddr'),
]

apps/orders/models.py
from django.db import models

from merchant.models import Goods, Project, Merchant
from orders.views_constant import ORDER_STATUS_NOT_PAY
from users.models import Users


class Cart(models.Model):
    c_user = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name='用户ID')
    c_goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='商品ID')

    c_goods_num = models.IntegerField(default=1, verbose_name='商品总数')
    c_is_select = models.BooleanField(default=True, verbose_name='商品是否选中')

    class Meta:
        db_table = 'chuan_cart'


class Order(models.Model):
    o_user = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name='用户ID')
    o_merchant = models.ForeignKey(Merchant, on_delete=models.CASCADE, verbose_name='商家ID')
    o_price = models.FloatField(default=0, verbose_name='订单价格')
    o_time = models.DateTimeField(auto_now_add=True, verbose_name='下单时间')
    o_status = models.IntegerField(default=ORDER_STATUS_NOT_PAY, verbose_name='订单状态')

    class Meta:
        db_table = 'chuan_order'


class OrderGoods(models.Model):
    o_order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='订单ID')
    o_goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='订单商品')
    o_goods_num = models.IntegerField(default=1, verbose_name='商品数量')

    class Meta:
        db_table = 'chuan_orderGoods'

apps/orders/views.py
import datetime

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from Chuan.settings import MEDIA_KEY_PREFIX
from merchant.models import Project, Goods
from orders.models import Cart, Order, OrderGoods
from orders.views_constant import ORDER_STATUS_NOT_RECEIVE, ORDER_STATUS_NOT_PAY, ORDER_STATUS_NOT_SEND
from orders.views_helper import get_total_price, get_total_price_ordering, get_order_status, get_cart_num
from users.models import Address, AddressCopy, Users


def hello(request):
    return HttpResponse('hah')


def project(request):
    projectid = request.GET.get('projectid')
    projects = Project.objects.get(pk=projectid)
    # 计算该用户发布项目总数
    projects_count = Project.objects.filter(p_merchant_id=projects.p_merchant.id).count()
    # 日期计算
    endtime = (projects.p_time + datetime.timedelta(days=projects.p_days)).strftime("%Y-%m-%d")
    endtimeStr = datetime.datetime.strptime(endtime, "%Y-%m-%d")
    nowtime = datetime.datetime.now()
    nowtimeStr = datetime.datetime.strptime(nowtime.strftime('%Y-%m-%d'), '%Y-%m-%d')
    remaining = endtimeStr - nowtimeStr
    goods_list = Goods.objects.filter(g_project_id=projects.id)
    # 项目支持人次计算
    sold = 0
    for goods in goods_list:
        # 商品库存计算
        goods.stock = goods.g_stock - goods.g_sold
        sold = sold + goods.g_sold

    data = {
        'title': '项目',
        'projects': projects,
        'goods_list': goods_list,
        'MEDIA_KEY_PREFIX': MEDIA_KEY_PREFIX,
        'sold': sold,
        'year': endtimeStr.year,
        'month': endtimeStr.month,
        'day': endtimeStr.day,
        'remaining': remaining.days,
        'projects_count': projects_count,
    }

    user_id = request.session.get('user_id')
    if user_id:
        user = Users.objects.get(pk=user_id)
        data['username'] = user.u_username
        data['is_login'] = True
        data['cart_num'] = get_cart_num(user_id)

    return render(request, 'main/project.html', context=data)


def add_to_cart(request):
    goodsid = request.GET.get('goodsid')
    carts = Cart.objects.filter(c_user=request.user).filter(c_goods_id=goodsid)
    if carts.exists():
        cart_obj = carts.first()
        cart_obj.c_goods_num = cart_obj.c_goods_num + 1
    else:
        cart_obj = Cart()
        cart_obj.c_goods_id = goodsid
        cart_obj.c_user = request.user
    cart_obj.save()
    data = {
        'status': 200,
        'msg': 'add success',
        'c_goods_num': cart_obj.c_goods_num
    }
    return JsonResponse(data)


def cart(request):
    carts = Cart.objects.filter(c_user=request.user)
    is_all_select = not carts.filter(c_is_select=False).exists()
    is_select = carts.filter(c_is_select=True)
    all_num = 0
    for num in is_select:
        all_num = num.c_goods_num + all_num
    list_carts = {}
    for cart in carts:
        if cart.c_goods.g_project not in list_carts:
            list_carts[cart.c_goods.g_project] = []
            list_carts[cart.c_goods.g_project].append(cart)
        else:
            list_carts[cart.c_goods.g_project].append(cart)

    data = {
        'title': '购物车',
        'carts': list_carts,
        'is_all_select': is_all_select,
        'total_price': get_total_price(request.user.id),
        'MEDIA_KEY_PREFIX': MEDIA_KEY_PREFIX,
        'all_num': all_num,
        'message': '购物车'
    }

    # 查询用户名
    user_id = request.user.id
    user = Users.objects.get(pk=user_id)
    data['username'] = user.u_username
    data['is_login'] = True
    # 查询购物车数量
    data['cart_num'] = get_cart_num(user_id)

    return render(request, 'orders/cart.html', context=data)


def change_cart_state(request):
    cart_id = request.GET.get('cartid')
    cart_obj = Cart.objects.get(pk=cart_id)
    cart_obj.c_is_select = not cart_obj.c_is_select
    cart_obj.save()
    is_all_select = not Cart.objects.filter(c_user=request.user).filter(c_is_select=False).exists()

    is_select = Cart.objects.filter(c_user=request.user).filter(c_is_select=True)
    all_num = 0
    for num in is_select:
        all_num = num.c_goods_num + all_num

    data = {
        'status': 200,
        'msg': 'change ok',
        'c_is_select': cart_obj.c_is_select,
        'is_all_select': is_all_select,
        'total_price': get_total_price(request.user.id),
        'all_num': all_num,
    }

    return JsonResponse(data=data)


def sub_subshopping(request):
    cart_id = request.GET.get('cartid')
    cart_obj = Cart.objects.get(pk=cart_id)
    data = {
        'status': 200,
        'msg': 'ok',
    }
    if cart_obj.c_goods_num > 1:
        cart_obj.c_goods_num = cart_obj.c_goods_num - 1
        cart_obj.save()
        data['c_goods_num'] = cart_obj.c_goods_num
        data['price_sum'] = cart_obj.c_goods_num * cart_obj.c_goods.g_price
    # else:
    #     cart_obj.delete()
    is_select = Cart.objects.filter(c_user=request.user).filter(c_is_select=True)
    all_num = 0
    for num in is_select:
        all_num = num.c_goods_num + all_num
    data['all_num'] = all_num
    data['total_price'] = get_total_price(request.user.id)
    return JsonResponse(data=data)


def add_subshopping(request):
    cart_id = request.GET.get('cartid')
    cart_obj = Cart.objects.get(pk=cart_id)
    data = {
        'status': 200,
        'msg': 'ok'
    }
    cart_obj.c_goods_num = cart_obj.c_goods_num + 1
    cart_obj.save()
    data['c_goods_num'] = cart_obj.c_goods_num
    data['price_sum'] = cart_obj.c_goods_num * cart_obj.c_goods.g_price
    is_select = Cart.objects.filter(c_user=request.user).filter(c_is_select=True)
    all_num = 0
    for num in is_select:
        all_num = num.c_goods_num + all_num
    data['all_num'] = all_num
    data['total_price'] = get_total_price(request.user.id)
    return JsonResponse(data=data)


def all_select(request):
    cart_list = request.GET.get('cart_list')
    cart_list = cart_list.split('#')
    carts = Cart.objects.filter(id__in=cart_list)
    for cart_obj in carts:
        cart_obj.c_is_select = not cart_obj.c_is_select
        cart_obj.save()

    is_select = Cart.objects.filter(c_user=request.user).filter(c_is_select=True)
    all_num = 0
    for num in is_select:
        all_num = num.c_goods_num + all_num

    data = {
        'status': 200,
        'msg': 'ok',
        'total_price': get_total_price(request.user.id),
        'all_num': all_num,
    }
    return JsonResponse(data=data)


def ordering(request):
    user_id = request.user.id
    address = Address.objects.filter(a_user_id=user_id).order_by('-a_is_default')
    cart_obj = Cart.objects.filter(c_user_id=user_id).filter(c_is_select=True)

    list_carts = {}
    for cart in cart_obj:
        if cart.c_goods.g_project not in list_carts:
            list_carts[cart.c_goods.g_project] = []
            list_carts[cart.c_goods.g_project].append(cart)
        else:
            list_carts[cart.c_goods.g_project].append(cart)

    is_select = Cart.objects.filter(c_user=request.user).filter(c_is_select=True)
    all_num = 0
    for num in is_select:
        all_num = num.c_goods_num + all_num

    data = {
        'title': '订单结算页',
        'address': address,
        'total_price': get_total_price(user_id),
        'MEDIA_KEY_PREFIX': MEDIA_KEY_PREFIX,
        'carts': list_carts,
        'all_num': all_num
    }

    # 查询用户名
    user_id = request.user.id
    user = Users.objects.get(pk=user_id)
    data['username'] = user.u_username
    data['is_login'] = True

    return render(request, 'orders/ordering.html', context=data)


def make_order(request):
    carts = Cart.objects.filter(c_user=request.user).filter(c_is_select=True)
    temp = []
    for cart in carts:
        if cart.c_goods.g_project_id not in temp:
            temp.append(cart.c_goods.g_project.id)
            cart_objs = Cart.objects.filter(c_user=request.user).filter(
                c_goods__g_project_id=cart.c_goods.g_project_id).filter(c_is_select=True)
            order = Order()
            order.o_user = request.user
            order.o_merchant = cart.c_goods.g_project.p_merchant
            order.o_price = get_total_price_ordering(request.user.id, cart.c_goods.g_project_id)
            order.save()
            addressid = request.GET.get('addressid')
            address = Address.objects.get(pk=addressid)
            address_copy = AddressCopy()
            address_copy.a_order = order
            address_copy.a_name = address.a_name
            address_copy.a_phone = address.a_phone
            address_copy.a_address = address.a_address
            address_copy.a_code = address.a_code
            address_copy.save()
            for cart_obj in cart_objs:
                orderGoods = OrderGoods()
                orderGoods.o_order = order
                orderGoods.o_goods_num = cart_obj.c_goods_num
                orderGoods.o_goods = cart_obj.c_goods
                orderGoods.save()
                cart_obj.delete()

    data = {
        'status': 200,
        'msg': 'ok',
        'order_id': order.id
    }

    return JsonResponse(data=data)


def order_detail(request):
    order_id = request.GET.get('orderid')
    order = Order.objects.get(pk=order_id)
    address = AddressCopy.objects.get(a_order_id=order_id)
    data = {
        'title': '订单详细',
        'order': order,
        'address': address,
        'status': get_order_status(order.o_status),
        'MEDIA_KEY_PREFIX': MEDIA_KEY_PREFIX
    }

    # 查询用户名
    user_id = request.user.id
    user = Users.objects.get(pk=user_id)
    data['username'] = user.u_username
    data['is_login'] = True
    # 查询订单数量
    data['cart_num'] = get_cart_num(user_id)
    return render(request, 'orders/orderdetail.html', context=data)


def order_list_not_pay(request):
    orders = Order.objects.filter(o_user=request.user).filter(o_status=ORDER_STATUS_NOT_PAY)
    data = {
        'title': '订单列表',
        'orders': orders,
        'MEDIA_KEY_PREFIX': MEDIA_KEY_PREFIX
    }

templates/orders/order_list_not_pay.html
{% extends 'base_orders.html' %}
{% load static %}

{% block ext_js %}
    {{ block.super }}
    <script src="{% static 'chuan/orders/js/order_list_not_pay.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="order_list_not_pay">
        <ol>
            {% for order in orders %}
                <li>
                    <ul class="order" orderid="{{ order.id }}">
                        <p>订单编号：{{ order.id }}</p>
                        {% for ordergoods in order.ordergoods_set.all %}
                            <li>
                                <img src="{{ MEDIA_KEY_PREFIX }}{{ ordergoods.o_goods.g_img }}" height="90px">
                                <p>{{ ordergoods.g_title }}</p>
                            <p>{{ order.o_price }}</p>
                            </li>
                        {% endfor %}
                        
                    </ul>
                </li>
            {% endfor %}

        </ol>
    </div>
{% endblock %}

templates/orders/orderdetail.html
{% extends 'base_orders.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'chuan/orders/css/orderdetail.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script src="{% static 'chuan/orders/js/order_detail.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="content">
        <div class="w">

            <div class="od-top">
                <a href="{% url 'users:mine' %}">我的众筹</a>
                <span>
                    &nbsp;>&nbsp;
                    <a href="{% url 'users:mine_order' %}">订单中心</a>
                    &nbsp;>&nbsp;
                    <strong>订单：{{ order.id }}</strong>
                </span>
            </div>

            <div class="od-status clear">
                <div class="state-lcol">
                    <div class="state-top">订单：{{ order.id }}</div>
                    <h3 class="state-txt">{{ status|first }}</h3>
                    <div class="state-btns"><a id="alipay" orderid="{{ order.id }}">{{ status|last }}</a></div>

                </div>
                <div class="od-addr">
                    <div class="dt"><h4>收货人信息</h4></div>
                    <div class="dd">收货人：{{ address.a_name }}</div>
                    <div class="dd">地址：{{ address.a_address }}</div>
                    <div class="dd">手机号：{{ address.a_phone }}</div>
                </div>
            </div>

            <div class="od-merchant">{{ order.ordergoods_set.first.o_goods.g_project.p_merchant.m_merchantName }}</div>

            <div class="od-goods">
                <div class="od-good-top clear">
                    <div class="od-good">商品</div>
                    <div class="od-price">价格</div>
                    <div class="od-num">数量</div>
                </div>

                {% for goods in order.ordergoods_set.all %}



                    <div class="od-good-content clear">
                        <div class="od-good-img">
                            <img src="{{ MEDIA_KEY_PREFIX }}{{ goods.o_goods.g_img }}" alt="">

                            <div class="od-good-title">{{ goods.o_goods.g_title }}</div>
                        </div>
                        <div class="od-good-price">￥{{ goods.o_goods.g_price }}</div>
                        <div class="od-good-price">{{ goods.o_goods_num }}</div>
                    </div>
                {% endfor %}
            </div>


            <div class="od-bottom clear">
                <div class="od-bottom-text clear">
                    <div class="od-bottom-money clear">商品总额：<span>¥{{ order.o_price }}</span></div>
                    <div class="clear"></div>
                    <div class="od-bottom-pay">应付总额：<span id="od-count">¥{{ order.o_price }}</span></div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}


{#{% block content %}#}
{#    <div class="container" id="order_detail">#}
{#        <p>订单编号：{{ order.id }}</p>#}
{#        <p>收货地址</p>#}
{#        <div>#}
{#            <p>{{ address.a_name }} {{ address.a_phone }} {{ address.a_code }}</p>#}
{#            <p>{{ address.a_address }}</p>#}
{#        </div>#}
{#        <ul>#}
{#            {% for ordergoods in order.ordergoods_set.all %}#}
{#                <li>#}
{#                    <img src="{{ MEDIA_KEY_PREFIX }}{{ ordergoods.o_goods.g_img }}" height="90px">#}
{#                    <p>{{ ordergoods.o_goods.g_title }}</p>#}
{#                    <p>{{ order.o_price }}</p>#}
{#                    <p>{{ ordergoods.o_goods_num }}</p>#}
{#                </li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#        <p id="total_price">总价：{{ order.o_price }}</p>#}
{#        <button >支付</button>#}
{#    </div>#}
{#{% endblock %}#}

templates/orders/ordering.html
{% extends 'base_orders.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'chuan/orders/css/ordering.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'chuan/orders/js/ordering.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="">
        <div class="headerBox">
            <div class="headerTop">
                <div class="headerTopRight">
                    {% if is_login %}
                        <p>您好，<a href="{% url 'users:mine' %}" style="color: #0f0f0f">{{ username }}</a>&nbsp;&nbsp;
                            <a href="{% url 'users:logout' %}" class="textTop">退出登录</a>&nbsp;|&nbsp;
                            <a href="{% url 'users:mine_order' %}" class="textTop">我的订单</a>
                            {% else %}
                        <p>您好，请&nbsp;<a href="{% url 'users:login' %}" class="mine-login">登录</a>&nbsp;&nbsp;
                        <a href="{% url 'users:register' %}" class="textTop">注册</a>&nbsp;|&nbsp;
                        <a href="{% url 'users:login' %}" class="textTop">我的订单</a>
                    {% endif %}
                    <img src="/static/img/icon/horn.png" alt="" id="horn">
                    <a href="#" class="textTop">网站公告</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="logoArea">
            <div class="logo" style="display: block">
                <a href="{% url 'index:indexs' %}"> <img class="logo-img" src="/static/img/icon/indexlogo.jpg"
                                                         alt=""></a>
            </div>
            <div class="logoText">
                <a href="{% url 'users:mine' %}">{{ message }}</a>
            </div>

        </div>
        <div class="clearfix"></div>
    </div>
{% endblock %}

{% block content %}
    <div class="content">
    <div>
        <span class="top-text">请核对订单信息</span>
    </div>
    <div class="checkout-steps">
    <div class="clear">
        <h3 class="step-tit" style="float: left;">收货人信息</h3>
        <div class="add-address">新增收货地址</div>
    </div>
    <div class="addr-detail clear">
        <ul id="address">
            {% for addr in address %}
                {% if addr.a_is_default == 1 %}
                    <li class="selected" addressid="{{ addr.id }}">
                        {% else %}
                    <li addressid="{{ addr.id }}">
                {% endif %}
            <span id="a-name">{{ addr.a_name }}</span>
            <span id="a-address">{{ addr.a_address }}</span>
            <span id="a-phone">{{ addr.a_phone }}</span>
            {#                    {% if addr.a_is_default %}#}
            {#                        <p>默认地址</p>#}
            {#                    {% endif %}#}
            </li>

            {% endfor %}
        </ul>
    </div>
    <div class="choose-pay">
        <div class="clear">
            <h3 class="step-tit">支付方式</h3>
            <ul>
                <li class="payment-item pay-selected">支付宝支付</li>
                <li class="payment-item">微信支付</li>
                <li class="payment-item">银联支付</li>
            </ul>
        </div>
    </div>
    <div class="goods-list">
        <h3 class="step-tit">送货清单</h3>

        {% for key, value in carts.items %}

            {% for cart in value %}
                {% if forloop.counter == 1 %}
                    <div>
                    <div class="merchant">{{ cart.c_goods.g_project.p_merchant.m_merchantName }}</div>
                {% endif %}

                <div class="pay-goods-list">
                    <div class="pay-goods-item clear">
                        <div class="pay-goods-img">
                            <img src="{{ MEDIA_KEY_PREFIX }}{{ cart.c_goods.g_img }}" alt="">
                        </div>
                        <div class="pay-goods-title">
                            <a href="#" target="_blank">
                                {{ cart.c_goods.g_project.p_title }}
                            </a>
                        </div>
                        <div class="pay-goods-price">
                            <div class="price">￥{{ cart.c_goods.g_price }}</div>
                        </div>
                        <div class="pay-goods-num">
                            <span>x{{ cart.c_goods_num }}</span>
                        </div>
                    </div>
                </div>

                {% if forloop.counter == 1 %}
                    <div>
                {% endif %}


            {% endfor %}
        {% endfor %}

        </div>
        <div class="pay-message">
            <div class="clear">
                <h3 class="step-tit">备注信息</h3>
                <div class="pay-msg">
                    <input type="text">
                </div>

            </div>
        </div>
        <div class="pay-count">
            <div class="pay-count-div">
                <div class="pay-count-num">
                    <span>{{ all_num }}&nbsp;件商品，总商品金额：</span><em>￥{{ total_price }}</em>
                </div>
                <div class="pay-count-money">
                    <span style="line-height: 22px">应付总额：</span><em class="em-money">￥{{ total_price }}</em>
                </div>
            </div>
            <div style="clear: both"></div>
            <div class="pay-count-addr">
                寄送至：{{ address.first.a_address }}&nbsp;收货人：{{ address.first.a_name }}&nbsp;{{ address.first.a_phone }}</div>
            <div class="pay-submit">
                <button id="make_order">提交订单</button>
            </div>

        </div>
        </div>
    </div>
{% endblock %}