Chuan/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls', namespace='index')),
    path('users/', include('users.urls', namespace='users')),
    path('merchant/', include('merchant.urls', namespace='merchant')),
    path('orders/', include('orders.urls', namespace='orders'))
]

apps/orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('project/', views.project, name='project'),
    path('addtocart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('changecartstate/', views.change_cart_state, name='change_cart_state'),
    path('subshopping/', views.sub_subshopping, name='sub_shopping'),
    path('addshopping/', views.add_subshopping, name='add_shopping'),
    path('allselect/', views.all_select, name='all_select'),
    path('ordering/', views.ordering, name='ordering'),
    path('makeorder/', views.make_order, name='make_order'),
    path('orderdetail/', views.order_detail, name='order_detail'),
    path('orderlistnotpay/', views.order_list_not_pay, name='order_list_not_pay'),
    path('payed/', views.payed, name='payed'),
]

apps/users/urls.py
from django.urls import path

from users import views

app_name = 'users'
urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('checkuser/', views.check_user, name='check_user'),
    path('checkemail/', views.check_email, name='check_email'),
    path('mine/', views.mine, name='mine'),
    path('logout/', views.logout, name='logout'),
    path('activate/', views.activate, name='activate'),
    path('mineorder/', views.mine_order, name='mine_order'),
    path('address/', views.address, name='address'),
    path('deleteaddr/', views.deleteaddr, name='deleteaddr'),
    path('defaultaddr/', views.defaultaddr, name='defaultaddr'),
]

apps/orders/models.py
from django.db import models

from merchant.models import Goods, Project, Merchant
from orders.views_constant import ORDER_STATUS_NOT_PAY
from users.models import Users


class Cart(models.Model):
    c_user = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name='用户ID')
    c_goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='商品ID')

    c_goods_num = models.IntegerField(default=1, verbose_name='商品总数')
    c_is_select = models.BooleanField(default=True, verbose_name='商品是否选中')

    class Meta:
        db_table = 'chuan_cart'


class Order(models.Model):
    o_user = models.ForeignKey(Users, on_delete=models.CASCADE, verbose_name='用户ID')
    o_merchant = models.ForeignKey(Merchant, on_delete=models.CASCADE, verbose_name='商家ID')
    o_price = models.FloatField(default=0, verbose_name='订单价格')
    o_time = models.DateTimeField(auto_now_add=True, verbose_name='下单时间')
    o_status = models.IntegerField(default=ORDER_STATUS_NOT_PAY, verbose_name='订单状态')

    class Meta:
        db_table = 'chuan_order'


class OrderGoods(models.Model):
    o_order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='订单ID')
    o_goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name='订单商品')
    o_goods_num = models.IntegerField(default=1, verbose_name='商品数量')

    class Meta:
        db_table = 'chuan_orderGoods'

apps/users/models.py
from django.db import models


class Users(models.Model):
    u_username = models.CharField(max_length=32, unique=True, verbose_name='用户名')
    u_password = models.CharField(max_length=256, verbose_name='用户密码')
    u_email = models.CharField(max_length=64, unique=True, verbose_name='用户邮箱')
    u_icon = models.ImageField(upload_to='icons/%Y/%m/%d', verbose_name='用户头像')
    is_active = models.BooleanField(default=False, verbose_name='用户激活状态')
    is_delete = models.BooleanField(default=False, verbose_name='用户是否删除')

    class Meta:
        db_table = 'chuan_user'


class Address(models.Model):
    a_name = models.CharField(max_length=16, verbose_name='收货姓名')
    a_phone = models.CharField(max_length=11, verbose_name='收货手机号码')
    a_address = models.CharField(max_length=256, verbose_name='收货地址')
    a_code = models.CharField(max_length=6, verbose_name='邮政编码')
    a_is_default = models.BooleanField(default=True, verbose_name='默认地址')
    a_user = models.ForeignKey(Users, verbose_name='用户ID', on_delete=models.CASCADE)

    class Meta:
        db_table = 'chuan_address'


class AddressCopy(models.Model):
    a_name = models.CharField(max_length=16, verbose_name='收货姓名')
    a_phone = models.CharField(max_length=11, verbose_name='收货手机号码')
    a_address = models.CharField(max_length=256, verbose_name='收货地址')
    a_code = models.CharField(max_length=6, null=True, verbose_name='邮政编码')
    a_order = models.ForeignKey('orders.Order', verbose_name='订单ID', on_delete=models.CASCADE)

    class Meta:
        db_table = 'chuan_addressCopy'

apps/users/views.py
import uuid

from django.contrib.auth.hashers import make_password, check_password
from django.core.cache import cache
from django.core.mail import send_mail
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.urls import reverse

from Chuan.settings import MEDIA_KEY_PREFIX
from merchant.models import Goods
from orders.models import Cart, Order
from orders.views_constant import ORDER_STATUS_NOT_PAY, ORDER_STATUS_NOT_SEND, ORDER_STATUS_NOT_RECEIVE
from orders.views_helper import get_cart_num, get_order_status
from users.models import Users, Address
from users.views_constant import HTTP_USER_EXIST, HTTP_OK, HTTP_EMAIL_EXIST
from users.views_helper import hash_str, send_email_activate


def hello(request):
    return None


def register(request):
    if request.method == "GET":
        data = {
            'title': '注册'
        }
        return render(request, 'user/register.html', context=data)
    elif request.method == "POST":
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        # password = hash_str(password)
        password = make_password(password)

        user = Users()
        user.u_username = username
        user.u_password = password
        user.u_email = email

        user.save()
        u_token = uuid.uuid4().hex
        cache.set(u_token, user.id, timeout=60 * 60)

        send_email_activate(username, email, u_token)

        return redirect(reverse('users:login'))


def login(request):
    if request.method == "GET":
        error_message = request.session.get('error_message')
        data = {
            'title': '登录'
        }
        if error_message:
            del request.session['error_message']
            data['error_message'] = error_message
        return render(request, 'user/login.html', context=data)
    elif request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        users = Users.objects.filter(Q(u_username=username) | Q(u_email=username))
        if users.exists():
            user = users.first()
            if check_password(password, user.u_password):
                if user.is_active:
                    request.session['user_id'] = user.id
                    return redirect(reverse('users:mine'))
                else:
                    request.session['error_message'] = '用户未激活'
                    redirect(reverse('users:login'))
            else:
                request.session['error_message'] = '密码错误'
                return redirect(reverse('users:login'))
        request.session['error_message'] = '用户不存在'
        return redirect(reverse('users:login'))


def check_user(request):
    username = request.GET.get('username')
    users = Users.objects.filter(u_username=username)
    data = {
        'status': HTTP_OK,
        'msg': 'username can user'
    }
    if users.exists():
        data['status'] = HTTP_USER_EXIST
        data['msg'] = 'user already exist'

    return JsonResponse(data=data)


def check_email(request):
    email = request.GET.get('email')
    emailcheck = Users.objects.filter(u_email=email)
    data = {
        'status': HTTP_OK,
        'msg': 'email can user'
    }
    if emailcheck.exists():
        data['status'] = HTTP_EMAIL_EXIST
        data['msg'] = 'user already exist'

    return JsonResponse(data=data)


def mine(request):
    user_id = request.user.id
    data = {
        'title': '我的众筹',
        'is_login': False,
        'cart_num': get_cart_num(user_id)
    }
    if user_id:
        user = Users.objects.get(pk=user_id)
        data['username'] = user.u_username
        data['is_login'] = True
        data['order_not_pay'] = Order.objects.filter(o_user=user).filter(o_status=ORDER_STATUS_NOT_PAY).count()
        data['order_not_receive'] = Order.objects.filter(o_user=user).filter(
            o_status__in=[ORDER_STATUS_NOT_RECEIVE, ORDER_STATUS_NOT_SEND]).count()

    return render(request, 'user/mine.html', context=data)


def logout(request):
    request.session.flush()
    return redirect(reverse('users:login'))


def activate(request):
    u_token = request.GET.get('u_token')
    print(u_token)
    user_id = cache.get(u_token)
    if user_id:
        cache.delete(u_token)
        user = Users.objects.get(pk=user_id)
        user.is_active = True
        user.save()
        return redirect(reverse('users:login'))
    return render(request, 'user/activate_fail.html')


def address(request):
    user_id = request.user.id
    if request.method == 'GET':
        data = {
            'title': '我的',
            'is_login': True
        }
        user = Users.objects.get(pk=user_id)
        data['username'] = user.u_username
        user_address = Address.objects.filter(a_user_id=user_id).order_by('-a_is_default')
        data['address'] = user_address
        data['cart_num'] = get_cart_num(user_id)
        return render(request, 'user/address.html', context=data)
    elif request.method == "POST":
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        address_detail = request.POST.get('address')
        code = request.POST.get("code")
        if request.POST.get('default'):
            default = True
            address_sure = Address.objects.filter(a_user_id=user_id).get(a_is_default=True)
            address_sure.a_is_default = False
            address_sure.save()
        else:
            default = False
            try:
                address_sure = Address.objects.filter(a_user_id=user_id).get(a_is_default=True)
            except Address.DoesNotExist:
                default = True
        address_obj = Address()
        address_obj.a_name = name
        address_obj.a_phone = phone
        address_obj.a_address = address_detail
        address_obj.a_code = code
        address_obj.a_is_default = default
        address_obj.a_user_id = user_id
        address_obj.save()
        return redirect(reverse('users:address'))


def mine_order(request):
    user_id = request.user.id
    user = Users.objects.get(pk=user_id)
    orders = Order.objects.filter(o_user_id=user_id).order_by('-id')
    for order in orders:
        order.o_status = get_order_status(order.o_status)
    data = {
        'title': '我的订单',
        'is_login': True,
        'username': user.u_username,
        'orders': orders,
        'MEDIA_KEY_PREFIX': MEDIA_KEY_PREFIX,
        'cart_num': get_cart_num(user_id)
    }
    # data['username'] = user.u_username
    # data['is_login'] = True
    # data['order_not_pay'] = Order.objects.filter(o_user=user).filter(o_status=ORDER_STATUS_NOT_PAY).count()
    # data['order_not_receive'] = Order.objects.filter(o_user=user).filter(
    # o_status__in=[ORDER_STATUS_NOT_RECEIVE, ORDER_STATUS_NOT_SEND]).count()
    return render(request, 'user/mine_order.html', context=data)


def deleteaddr(request):
    addrid = request.GET.get('addrid')
    addressid = Address.objects.get(pk=addrid)
    addressid.delete()
    data = {
        'status': 200
    }
    return JsonResponse(data=data)


def defaultaddr(request):
    addrid = request.GET.get('addrid')
    addrold = Address.objects.get(a_is_default=True)
    addrold.a_is_default = not addrold.a_is_default
    addrold.save()
    addrnew = Address.objects.get(pk=addrid)
    addrnew.a_is_default = not addrnew.a_is_default
    addrnew.save()
    data = {
        'status': 200,
        'addr_name': addrnew.a_name
    }
    return JsonResponse(data=data)

templates/user/activate.html
<h4>Dear {{ username }}:</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;欢迎注册川众筹，您的账号没有进行激活验证，请点击下面的激活按钮</p>
<a href="{{ activate_url }}">激活</a>
<p>如上面的激活按钮不可用，请将下面的地址复制到浏览器进行激活</p>
<p>{{ activate_url }}</p>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;Best Wishes</h4>
<p>From ChuanOfficial</p>

templates/user/activate_fail.html
{% extends 'base_user.html' %}

{% block content %}
    <div>
        <h3>激活失败，请重新申请激活</h3>
    </div>
{% endblock %}

templates/user/address.html
{% extends 'user/mine.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'chuan/user/css/address.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'chuan/user/js/address.js' %}"></script>
{% endblock %}

{% block main %}

    <div class="addressList">
        <div class="mt">
            <a href="#" class="add-btn" onclick="addAddressDiag()">新增收货地址</a>
        </div>

        <div class="mc">
            {% for addr in address %}
                <div class="sm">
                    <div class="smt">
                        <h3 style="font-size: 18px">{{ addr.a_name }}
                            {% if addr.a_is_default == 1 %}
                                <span>默认地址</span>
                            {% else %}
                            {% endif %}
                        </h3>
                    </div>

                    <div class="smc" addrid="{{ addr.id }}">
                        <div class="items">
                            <div class="item"><span>收货人：</span>
                                <div class="fl">{{ addr.a_name }}</div>
                                <div class="clr"></div>
                            </div>
                            <div class="item"><span>地址：</span>
                                <div class="fl">{{ addr.a_address }}</div>
                                <div class="clr"></div>
                            </div>
                            <div class="item"><span>手机：</span>
                                <div class="fl">{{ addr.a_phone }}</div>
                                <div class="clr"></div>
                            </div>
                            <div class="item"><span>邮政编码：</span>
                                <div class="fl">{{ addr.a_code }}</div>
                                <div class="clr"></div>
                            </div>
                            <div class="extra">
                                <a href="###" class="aText set_default">设为默认</a>
                                <button class="aText delete-addr">删除</button>
                            </div>
                        </div>

                        <div class="clr"></div>
                    </div>
                </div>
            {% endfor %}

        </div>

    </div>



    <div class="thickdiv" id="myModal1" style="display: none"></div>
    <div class="thickbox" style="display: none">
        <div class="thickwrap">
            <div class="thicktitle">
                <span>添加收货地址</span>
            </div>
            <div class="thickcon">
                <div class="addressDiagDiv">
                    <div class="mc-addr">
                        <div class="form">
                            <form action="{% url 'users:address' %}" method="POST" id="formId">
                                {% csrf_token %}
                                <div class="item-addr">
                                    <span class="label"><em>*</em>收货人：</span>
                                    <div class="fl-addr">
                                        <input id="name" type="text" class="text" name="name">
                                        <span id="" class="error-msg hide"></span>
                                    </div>
                                    <div class="clr"></div>
                                </div>
                                <div class="item-addr">
                                    <span class="label"><em>*</em>详细地址：</span>
                                    <div class="fl-addr">
                                        <input id="address" type="text" class="text"
                                               style="width: 484px" name="address">
                                        <span id="" class="error-msg hide"></span>
                                    </div>
                                    <div class="clr"></div>
                                </div>
                                <div class="item-addr">
                                    <span class="label"><em>*</em>手机号码：</span>
                                    <div class="fl-addr">
                                        <input id="phone" type="text" class="text" name="phone">
                                        <span id="" class="error-msg hide"></span>
                                    </div>
                                    <div class="clr"></div>
                                </div>
                                <div class="item-addr">
                                    <span class="label">邮政编码：</span>
                                    <div class="fl-addr">
                                        <input id="code" type="text" class="text" name="code">
                                        <span id="" class="error-msg hide"></span>
                                    </div>
                                    <div class="clr"></div>
                                </div>
                                <div class="btns">
                                    <a class="e-btn btn-9 save-btn"
                                       onclick="document:formId.submit()">保存收货地址</a>
                                </div>

                                <a href="#" class="thickclose" id="closeMyModal1">×</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#        {% for addr in address %}#}
    {#            <div>#}
    {#                <p>{{ addr.a_name }}{{ addr.a_phone }}{{ addr.a_code }}</p>#}
    {#                <p>{{ addr.a_address }}</p>#}
    {#                {% if addr.a_is_default %}#}
    {#                    <p>默认地址</p>#}
    {#                {% endif %}#}
    {#            </div>#}
    {#        {% endfor %}#}
    {#    </div>#}
    {#    <form method="post" action="{% url 'users:address' %}">#}
    {#        {% csrf_token %}#}
    {#        <div>#}
    {#            <h6>添加地址</h6>#}
    {#            <div class="form-group">#}
    {#                <label for="name">收货人</label>#}
    {#                <input type="text" id="name" name="name">#}
    {#            </div>#}
    {#            <div class="form-group">#}
    {#                <label for="phone">手机号</label>#}
    {#                <input type="text" id="phone" name="phone">#}
    {#            </div>#}
    {#            <div class="form-group">#}
    {#                <label for="address">详细地址</label>#}
    {#                <input type="text" id="address" name="address">#}
    {#            </div>#}
    {#            <div class="form-group">#}
    {#                <label for="code">邮政编码</label>#}
    {#                <input type="text" id="code" name="code">#}
    {#            </div>#}
    {#            <div class="form-group">#}
    {#                <input type="checkbox" name="default">设为默认地址#}
    {#            </div>#}
    {#            <div class="form-group">#}
    {#                <button type="submit">添加收货地址</button>#}
    {#            </div>#}
    {#        </div>#}
    {#    </form>#}
{% endblock %}

templates/user/login.html
{% extends 'base_user.html' %}
{% load static %}

{% block ext_css %}
    <link rel="stylesheet" href="{% static 'chuan/user/css/login.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'chuan/user/js/login.js' %}"></script>
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="text-right merchant">
            <a href="{% url 'merchant:login' %}">
                <button class="btn btn-info">去商家版</button>
            </a>
        </div>
        <div class="all-center">
            <div class="user-logo">
                <img class="center-block logo-img" src="/static/img/icon/header.png" alt="">
            </div>
            <form method="post" action="{% url 'users:login' %}" onsubmit="return parse_data()">

                {% csrf_token %}

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2 col-md-push-3 text-tip">
                            <label for="username_input">用户名</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="username" type="text" class="form-control" id="username_input"
                                   placeholder="用户名/手机号/邮箱">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="username_info" class="text-tip error_message">
                                {% if error_message == '用户不存在' or error_message == '用户未激活' %}
                                    {{ error_message }}
                                {% endif %}
                            </span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-3 text-tip">
                            <label for="password_input">密码</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="password" type="password" class="form-control" id="password_input"
                                   placeholder="请输入密码">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="password_info" class="text-tip error_message">
                                {% if error_message == '密码错误' %}
                                    {{ error_message }}
                                {% endif %}
                            </span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-7 col-md-push-3 loginbtn">
                            <button type="submit" class="btn btn-success btn-lg btn-block">登录</button>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-7 col-md-push-4 registerbtn">
                            <h2>未拥有账号><a href="{% url 'users:register' %}">去注册</a></h2>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/user/mine.html
{% extends 'base_user.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'chuan/user/css/mine.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script src="{% static 'chuan/user/js/mine.js' %}"></script>
{% endblock %}


{% block main %}
    {{ block.supwer }}
    <div class="userIcon">
        <a href="">
            <img src="{% static 'img/icon/default_icon.png' %}" alt="">
        </a>
    </div>
{% endblock %}

templates/user/mine_order.html
{% extends 'user/mine.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'chuan/user/css/mine_order.css' %}">
{% endblock %}

{% block main %}
    <div class="mainTip">
        <div>我的订单</div>
    </div>

    <div class="myOrder">
        <div class="mt">
            <ul>
                <li><a href="#" class="selected">全部订单</a></li>
                <li><a href="#" class="notSelect">待付款</a></li>
                <li><a href="#" class="notSelect">待收货</a></li>
                <li><a href="#" class="notSelect">待评价</a></li>
            </ul>
        </div>


        <div class="mc">

            <table>
                <thead>
                <tr>
                    <th>订单详细</th>
                    <th>收货人</th>
                    <th>金额</th>
                    <th>订单状态</th>
                    <th>操作</th>
                </tr>
                </thead>

                {% for order in orders %}
                    <tbody>
                    <tr class="sep-row">
                        <td colspan="5"></td>
                    </tr>
                    <tr class="tr-th">
                        <td colspan="5"><p>{{ order.o_time }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;订单号:{{ order.id }}</p></td>
                    </tr>


                    {% for goods in order.ordergoods_set.all %}
                        <tr class="tr-bd">
                            <td class="goods-detail">
                                <div class="goods-item">
                                    <div class="g-img"><img src="{{ MEDIA_KEY_PREFIX }}{{ goods.o_goods.g_img }}" alt=""
                                                            class="goods-img"></div>
                                    <div class="p-msg"><a href="">
                                        {{ goods.o_goods.g_project.p_merchant.m_merchantName }}&nbsp;&nbsp;{{ goods.o_goods.g_title }}</a>
                                    </div>
                                    <div class="goods-number">x{{ goods.o_goods_num }}</div>

                                </div>
                            </td>

                            {% if forloop.counter == 1 %}
                                <td rowspan="{{ order.ordergoods_set.all.count }}">{{ order.addresscopy_set.first.a_name }}</td>
                                <td rowspan="{{ order.ordergoods_set.all.count }}">总额 ¥{{ order.o_price }} <br> <br>
                                    在线支付
                                </td>
                                <td rowspan="{{ order.ordergoods_set.all.count }}">{{ order.o_status|first }} <br> <br> <a href="{% url 'orders:order_detail' %}?orderid={{ order.id }}">订单详情</a></td>
                                <td rowspan="{{ order.ordergoods_set.all.count }}">查看发票</td>
                            {% endif %}

                        </tr>
                    {% endfor %}

                    </tbody>
                {% endfor %}


            </table>
        </div>

    </div>

{% endblock %}

templates/user/register.html
{% extends 'base_user.html' %}
{% load static %}

{% block ext_css %}
    <link rel="stylesheet" href="{% static 'chuan/user/css/register.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'chuan/user/js/register.js' %}"></script>
{% endblock %}

{% block header %}

{% endblock %}

{% block content %}
    <div class="container">
        <div class="text-right merchant">
            <a href="{% url 'merchant:register' %}">
                <button class="btn btn-info">去商家版</button>
            </a>
        </div>

        <div class="all-center">
            <div class="user-logo">
                <img class="center-block logo-img" src="/static/img/icon/header.png" alt="">
            </div>
            <form method="post" action="{% url 'users:register' %}" onsubmit="return check()">

                {% csrf_token %}

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-2 col-md-push-3 text-tip">
                            <label for="username_input">用户名</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="username" type="text" class="form-control" id="username_input"
                                   placeholder="请输入用户名" aria-describedby="basic-addon1">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="username_info" class="text-tip"></span>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="row">
                        <div class="col-md-2 col-md-push-3 text-tip">
                            <label for="email_input">邮箱</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="email" type="text" class="form-control" id="email_input"
                                   placeholder="请输入邮箱">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="email_info" class="text-tip"></span>
                        </div>
                    </div>


                    <div class="clearfix"></div>


                    <div class="row">
                        <div class="col-md-2 col-md-push-3 text-tip">
                            <label for="password_input">密码</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="password" type="password" class="form-control" id="password_input"
                                   placeholder="请输入密码">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="password_info" class="text-tip"></span>
                        </div>
                    </div>


                    <div class="clearfix"></div>


                    <div class="row">
                        <div class="col-md-2 col-md-push-3 text-tip">
                            <label for="password_confirm_input" style="font-size: 13.5px;">确认密码</label>
                        </div>
                        <div class="col-md-6 col-md-push-2">
                            <input name="password_confirm" type="password" class="form-control"
                                   id="password_confirm_input"
                                   placeholder="请再次输入密码">
                        </div>
                        <div class="col-md-4 col-md-push-2">
                            <span id="password_confirm_info" class="text-tip"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-7 col-md-push-3 registerbtn">
                            <button type="submit" class="btn btn-primary btn-lg btn-block" id="button">注册</button>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-7 col-md-push-5 registerbtn">
                            <h2>已有账号><a href="{% url 'users:login' %}">去登录</a></h2>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
{% endblock %}